import { validateMarkdownFences } from "@llm-output-guard/core";

export const validateMarkdownOutputDescription =
  "Validate Markdown output generated by an LLM and detect broken or suspicious code fences.";

export function validateMarkdownOutput(text: string) {
  return validateMarkdownFences(text);
}
